# Generated by Django 2.2.24 on 2022-06-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='isdefault',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.EmailField(max_length=100),
        ),
    ]
